### PR TITLE
Feat/offline friendly

### PR DESCRIPTION
**Pull request by zachferland**
* DO NOT MERGE * WIP

Making changes to make it more friendly to run locally. Currently using this branch in a docker container.

Need some help getting AWS KMS to work, have it working fine on my own machine, but could not get it work in inside a docker container, so just going around it here temporarily. 

Want to do add docs or a dockerfile for getting postgres to work locally. Took me a lot of wrangling to finally get an instance working entirely locally.

### CODE REVIEW

**Comment by c-castillo** [comment]
@zachferland I can help you out with a `docker-compose.yml` file that links the service with the postgres container. It will also be useful for AWS KMS, since you only to pass the environment variables to make it work, and docker-compose accept the injection of env vars

**Comment by zachferland** [comment]
thanks @c-castillo ! I got it all wired up in a docker-compose.yml file, postgres + app, just took a little while :) I just couldn't get AWS KMS to work yet, so this commit just has that commented out, but yeah need to add back in properly. I ll show you were I was trying it out later

**Comment by oed** [comment]
Anything blocking getting this over the line? Seems like it should be simple now that the new serverless-kms-secrets supports the latest serverless version.

**Comment by oed** [comment]
Closing, this should already be addresses.

**Pull request closed without merging**
